package cmd

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

var (
	initOutPath string
	initForce   bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive setup — writes sharkauth.yaml",
	Long: `shark init asks three questions (base URL, admin email, SMTP choice)
and writes a ready-to-run sharkauth.yaml.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !isatty.IsTerminal(os.Stdin.Fd()) && !isatty.IsCygwinTerminal(os.Stdin.Fd()) {
			return errors.New("shark init requires an interactive terminal; run `shark init` directly or copy sharkauth.local.yaml as a template")
		}

		if _, err := os.Stat(initOutPath); err == nil && !initForce {
			return fmt.Errorf("%s already exists — re-run with --force to overwrite", initOutPath)
		}

		answers, err := askQuestions(os.Stdin, os.Stdout)
		if err != nil {
			return err
		}

		secret, err := randomHexN(32)
		if err != nil {
			return fmt.Errorf("generate secret: %w", err)
		}

		content := renderYAML(answers, secret)
		if err := os.WriteFile(initOutPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", initOutPath, err)
		}
		fmt.Printf("\n  wrote %s\n", initOutPath)
		fmt.Println("  next: shark serve")
		fmt.Println()
		return nil
	},
}

type initAnswers struct {
	BaseURL      string
	AdminEmail   string
	SMTPProvider string // "resend", "smtp", "none"
}

func askQuestions(stdin io.Reader, stdout io.Writer) (initAnswers, error) {
	r := bufio.NewReader(stdin)
	var a initAnswers

	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  SharkAuth setup — 3 questions.")
	fmt.Fprintln(stdout)

	a.BaseURL = prompt(r, stdout, "Base URL", "http://localhost:8080")
	a.AdminEmail = prompt(r, stdout, "Admin email", "")
	a.SMTPProvider = prompt(r, stdout, "Email provider (resend / smtp / none)", "resend")

	switch a.SMTPProvider {
	case "resend", "smtp", "none":
	default:
		return a, fmt.Errorf("invalid email provider %q: choose resend, smtp, or none", a.SMTPProvider)
	}

	return a, nil
}

func prompt(r *bufio.Reader, out io.Writer, label, def string) string {
	if def != "" {
		fmt.Fprintf(out, "  %s [%s]: ", label, def)
	} else {
		fmt.Fprintf(out, "  %s: ", label)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// renderYAML writes only the 3 required vars plus a commented-out override
// block. Everything else falls back to defaults baked into config.Load — keeps
// the generated file under 20 lines so new users aren't intimidated.
func renderYAML(a initAnswers, secret string) string {
	var emailBlock string
	switch a.SMTPProvider {
	case "resend":
		emailBlock = `email:
  provider: "resend"
  api_key: "${RESEND_API_KEY}"       # required: from resend.com
  from: "` + a.AdminEmail + `"
`
	case "smtp":
		emailBlock = `email:
  provider: "smtp"
  host: "${SMTP_HOST}"
  port: 587
  username: "${SMTP_USERNAME}"
  password: "${SMTP_PASSWORD}"
  from: "` + a.AdminEmail + `"
`
	default:
		emailBlock = `# email: not configured — run ` + "`shark serve --dev`" + ` for the dev inbox
`
	}

	return `# Generated by shark init. Minimal config: the 3 required vars below.
# Every other setting has a sensible default — see sharkauth.com/docs/config
# for the full reference.

server:
  secret: "` + secret + `"              # required: 32+ bytes, encrypts sessions
  base_url: "` + a.BaseURL + `"         # required: determines cookie/origin

` + emailBlock
}

func randomHexN(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func init() {
	initCmd.Flags().StringVar(&initOutPath, "out", "sharkauth.yaml", "output path")
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite if exists")
}
