package cmd

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

var (
	initOutPath string
	initForce   bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive setup — writes sharkauth.yaml",
	Long: `shark init asks three questions (base URL, admin email, SMTP choice)
and writes a ready-to-run sharkauth.yaml.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !isatty.IsTerminal(os.Stdin.Fd()) && !isatty.IsCygwinTerminal(os.Stdin.Fd()) {
			return errors.New("shark init requires an interactive terminal; run `shark init` directly or copy sharkauth.local.yaml as a template")
		}

		if _, err := os.Stat(initOutPath); err == nil && !initForce {
			return fmt.Errorf("%s already exists — re-run with --force to overwrite", initOutPath)
		}

		answers, err := askQuestions(os.Stdin, os.Stdout)
		if err != nil {
			return err
		}

		secret, err := randomHexN(32)
		if err != nil {
			return fmt.Errorf("generate secret: %w", err)
		}

		content := renderYAML(answers, secret)
		if err := os.WriteFile(initOutPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", initOutPath, err)
		}
		fmt.Printf("\n  wrote %s\n", initOutPath)
		fmt.Println("  next: shark serve")
		fmt.Println()
		return nil
	},
}

type initAnswers struct {
	BaseURL      string
	AdminEmail   string
	SMTPProvider string // "resend", "smtp", "none"
}

func askQuestions(stdin io.Reader, stdout io.Writer) (initAnswers, error) {
	r := bufio.NewReader(stdin)
	var a initAnswers

	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  SharkAuth setup — 3 questions.")
	fmt.Fprintln(stdout)

	a.BaseURL = prompt(r, stdout, "Base URL", "http://localhost:8080")
	a.AdminEmail = prompt(r, stdout, "Admin email", "")
	a.SMTPProvider = prompt(r, stdout, "Email provider (resend / smtp / none)", "resend")

	switch a.SMTPProvider {
	case "resend", "smtp", "none":
	default:
		return a, fmt.Errorf("invalid email provider %q: choose resend, smtp, or none", a.SMTPProvider)
	}

	return a, nil
}

func prompt(r *bufio.Reader, out io.Writer, label, def string) string {
	if def != "" {
		fmt.Fprintf(out, "  %s [%s]: ", label, def)
	} else {
		fmt.Fprintf(out, "  %s: ", label)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

func renderYAML(a initAnswers, secret string) string {
	var smtpBlock string
	switch a.SMTPProvider {
	case "resend":
		smtpBlock = `smtp:
  host: "smtp.resend.com"
  port: 465
  username: "resend"
  password: "${RESEND_API_KEY}"
  from: "` + a.AdminEmail + `"
  from_name: "SharkAuth"
`
	case "smtp":
		smtpBlock = `smtp:
  host: "${SMTP_HOST}"
  port: 587
  username: "${SMTP_USERNAME}"
  password: "${SMTP_PASSWORD}"
  from: "` + a.AdminEmail + `"
  from_name: "SharkAuth"
`
	default:
		smtpBlock = `# smtp: configure or run with --dev for the dev inbox
`
	}

	return `# Generated by shark init
server:
  port: 8080
  secret: "` + secret + `"
  base_url: "` + a.BaseURL + `"
  cors_origins: []

storage:
  path: "./data/sharkauth.db"

auth:
  session_lifetime: "30d"
  password_min_length: 8

magic_link:
  token_lifetime: "10m"
  redirect_url: "` + a.BaseURL + `/auth/callback"

password_reset:
  redirect_url: "` + a.BaseURL + `/auth/reset-password"

` + smtpBlock + `
mfa:
  issuer: "SharkAuth"
  recovery_codes: 10

api_keys:
  default_rate_limit: 1000
  key_max_lifetime: "365d"

audit:
  retention: "0"
  cleanup_interval: "1h"
`
}

func randomHexN(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func init() {
	initCmd.Flags().StringVar(&initOutPath, "out", "sharkauth.yaml", "output path")
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite if exists")
}
