package cmd

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

var (
	initOutPath string
	initForce   bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive setup — writes sharkauth.yaml",
	Long: `shark init asks three questions (base URL, admin email, SMTP choice)
and writes a ready-to-run sharkauth.yaml.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !isatty.IsTerminal(os.Stdin.Fd()) && !isatty.IsCygwinTerminal(os.Stdin.Fd()) {
			return errors.New("shark init requires an interactive terminal; run `shark init` directly or copy sharkauth.local.yaml as a template")
		}

		if _, err := os.Stat(initOutPath); err == nil && !initForce {
			return fmt.Errorf("%s already exists — re-run with --force to overwrite", initOutPath)
		}

		answers, err := askQuestions(os.Stdin, os.Stdout)
		if err != nil {
			return err
		}

		secret, err := randomHexN(32)
		if err != nil {
			return fmt.Errorf("generate secret: %w", err)
		}

		content := renderYAML(answers, secret)
		if err := os.WriteFile(initOutPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", initOutPath, err)
		}
		fmt.Printf("\n  wrote %s\n", initOutPath)
		printPostInitNotice(os.Stdout)
		return nil
	},
}

type initAnswers struct {
	BaseURL string
}

func askQuestions(stdin io.Reader, stdout io.Writer) (initAnswers, error) {
	r := bufio.NewReader(stdin)
	var a initAnswers

	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  SharkAuth setup.")
	fmt.Fprintln(stdout)

	a.BaseURL = prompt(r, stdout, "Base URL", "http://localhost:8080")

	return a, nil
}

// printPostInitNotice tells the operator how to go from "just ran shark init"
// to "ready for production email". Default provider is shark.email (testing
// tier) — call this out loudly so nobody ships user-facing flows on it.
func printPostInitNotice(out io.Writer) {
	fmt.Fprintln(out)
	fmt.Fprintln(out, "  Email: using shark.email (testing tier). Do not use for production flows.")
	fmt.Fprintln(out, "  Switch to your real provider via one of:")
	fmt.Fprintln(out, "    - edit email: in sharkauth.yaml")
	fmt.Fprintln(out, "    - run: shark email setup")
	fmt.Fprintln(out, "    - Settings → Email in the admin dashboard")
	fmt.Fprintln(out, "  Docs: https://sharkauth.com/docs")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "  next: shark serve")
	fmt.Fprintln(out)
}

func prompt(r *bufio.Reader, out io.Writer, label, def string) string {
	if def != "" {
		fmt.Fprintf(out, "  %s [%s]: ", label, def)
	} else {
		fmt.Fprintf(out, "  %s: ", label)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// renderYAML writes the minimum viable config: 3 vars (secret auto-generated,
// base_url asked, email provider defaults to shark.email testing tier).
// Everything else falls back to defaults baked into config.Load.
//
// Default email.provider is "shark" so `shark serve` works end-to-end with
// zero extra steps. Operators switch to resend/smtp/ses via YAML, CLI
// (`shark email setup`), or the dashboard.
func renderYAML(a initAnswers, secret string) string {
	return `# Generated by shark init. Minimum config — everything else has defaults.
# Full reference: https://sharkauth.com/docs/config

server:
  secret: "` + secret + `"              # required: 32+ bytes, encrypts sessions
  base_url: "` + a.BaseURL + `"         # required: determines cookie/origin

email:
  provider: "shark"                     # shark.email testing tier — switch before production
  # Switch to your real provider via:
  #   - edit this block (provider: resend | smtp | ses | postmark | mailgun)
  #   - shark email setup
  #   - Settings → Email in the admin dashboard
  # Docs: https://sharkauth.com/docs/email
`
}

func randomHexN(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func init() {
	initCmd.Flags().StringVar(&initOutPath, "out", "sharkauth.yaml", "output path")
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite if exists")
}
